baseURL: 'https://hugo.terrible.dk/'
staticDir:
  - static
  - /home/fred/Pictures
languageCode: en-us
canonifyURLs: true
title: Terrible
theme: lugo
sectionPagesMenu: not-main #for avoid to index folders (cours ingredients etc..) 
enableEmoji: true
defaultContentLanguage: en
enableMissingTranslationPlaceholders: true
languages:
  en:
    languageName: English
    title: terrible
    weight: 1
    permalinks:
      recipes: '/recipes/:slugorfilename/'
    params:
      linkedin: 'https://linkedin.com/en/whoever'
  da:
    languageName: Danish
    title: terrible
    weight: 0
    permalinks:
      recipes: '/opskrifter/:slugorfilename/'
    params:
      linkedin: 'https://linkedin.com/da/whoever'
      navigation:
        help: hælp
params:
  favicon: /favicon.svg
  stylesheet: /style.css
  indexarticles: 50
  taglist: true
  showrss: true
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      autoHeadingID: true
      autoHeadingIDType: github
      attribute:
        block: true
        title: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: true
taxonomies:
  category: categories
  tag: tags
  lang: lang
  
# MENU #  
menu:
  main:
    - name: shop
      pre: 
      post: basket
      url: 'https://www.terrible.dk'
      weight: -100
     
  
security:
  enableInlineShortcodes: false
  exec:
    allow:
      - ^dart-sass-embedded$
      - ^go$
      - ^npx$
      - ^postcss$
      - ^pandoc$
      - ^nvim$
      - pandoc
    osEnv:
      - (?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$
  funcs:
    getenv:
      - ^HUGO_
  http:
    methods:
      - (?i)GET|POST
    urls:
      - .*
