baseURL = 'https://based.cooking/'
languageCode = 'en-us'
title = 'Terrible'
theme = 'lugo'
sectionPagesMenu = "main"
enableEmoji = true
defaultContentLanguage = 'en'
enableMissingTranslationPlaceholders= true
  [languages.en]
   # baseURL = 'https://example.en'
    languageName = 'English'
    title = 'terrible'
    weight = 0
    [languages.en.permalinks]
      recipes = '/recipes/:slugorfilename/'
    [languages.en.params]
      linkedin = 'https://linkedin.com/en/whoever'
  [languages.da]
   #baseURL = 'https://example.da'
    languageName = 'Danish'
    title = 'terrible'
    weight = 1
    [languages.da.permalinks]
      recipes = '/opskrifter/:slugorfilename/'
      #recipes = '/opskrifter/'
    [languages.da.params]
      linkedin = 'https://linkedin.com/da/whoever'
      [languages.da.params.navigation]
      help = 'hælp'



[params]
  favicon = "/favicon.svg"
  stylesheet = "/style.css"
  indexarticles = 50
  taglist = true
  showrss = true


 
  [markup]
  #defaultMarkdownHandler = "pandoc"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = true

[taxonomies]
  category = 'categories'
  tag = 'tags'
  lang='lang'




[menu]
[[menu.main]]
  name = 'Terrible'
  post = "<span class='alert'>New!</span>"
  pre = "<i class='fa fa-road'></i>"
  url =  'https://www.terrible.dk'
  weight = -100
[[menu.main]]
  name= "contact"
  parent= ""
  weight= 100
  url =  '/contact/'
[[menu.main]]
  name= "about"
  parent= ""
  weight= 200
  url =  '/about/'  




[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^pandoc$', '^nvim$', 'pandoc']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

  [security.funcs]
    getenv = ['^HUGO_']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']