baseURL: 'https://hugo.terrible.dk/'
staticDir:
  - static
languageCode: en-us
canonifyURLs: true
title: Terrible

#theme: lugo
theme : rugo

sectionPagesMenu: notmain #not-main #for avoid to index folders (cours ingredients etc..) 
enableEmoji: true
defaultContentLanguage: en
enableMissingTranslationPlaceholders: true
languages:
  en:
    languageName: English
    title: terrible
    weight: 1
    permalinks:
     # recipes: '/recipes/:title/' # slugorfilename 
    params:
      navigation:
        help: hælp
  da:
    languageName: Danish
    title: terrible
    weight: 0
    permalinks: 
     # recipes: '/opskrifter/:title/' # slugorfilename
    params:
      navigation:
        help: hælp
params:
  favicon: /favicon.svg
  author: Frédéric Terrible


  featured_image: /images/01.jpg
  indexarticles: 50
  taglist: true
  showrss: true
  stylesheet: /style.css  #lugo

  facebook: 'https://www.facebook.com/terrible.dk/' # rugo
  instagram: 'https://www.instagram.com/terrible.dk/' # rugo
  site_logo: /images/logo.png # rugo
  background_color_class: bg-black-10 # rugo
  text_color: dark-gray # rugo
  custom_css : ["/customa.css"] # rugo


markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      autoHeadingID: true
      autoHeadingIDType: github
      attribute:
        block: true
        title: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: true
taxonomies:
  category: categories
  tag: tags
  lang: lang
  
# MENU #  
menu:
  main:
    - name: shop
      pre: 
      post: basket
      url: 'https://www.terrible.dk'
      weight: -100
     
  
security:
  enableInlineShortcodes: false
  exec:
    allow:
      - ^dart-sass-embedded$
      - ^go$
      - ^npx$
      - ^postcss$
      - ^pandoc$
      - ^nvim$
      - pandoc
    osEnv:
      - (?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$
  funcs:
    getenv:
      - ^HUGO_
  http:
    methods:
      - (?i)GET|POST
    urls:
      - .*
